### ISSUE TITLE
Gist is 404

### ISSUE THREAD

**Issue by Zireael07** [Cirru/parser.coffee#26]
(And I think so are ALL the gist on that account, or at least all linked to on cirru.org)

**Comment by tiye** [comment]
please give more details, what "gist" refers to?

**Comment by tiye** [comment]
if you just want to know what I've explored in visual programming(not quote though...), just check out the videos I posted https://space.bilibili.com/14227306/search/video?keyword=cirru .

**Comment by Zireael07** [comment]
"Here's a gist showing how it's parsed: " in the README

**Comment by tiye** [comment]
@Zireael07 I changed my main account so now it's https://gist.github.com/tiye/bdda3f616ff0f1bea917

**Comment by Zireael07** [comment]
Thanks - you might want to update the README then

**Comment by tiye** [comment]
sure https://github.com/Cirru/parser.coffee/commit/fd899f74d4fa3ce51bf4878a9aa957448245cc05
